### ISSUE TITLE
`Popover` without curtain throws error when clicking studio button

### ISSUE THREAD

**Issue by maxmmyron** [rendajs/Renda#508]
In cases where a Popover has no curtain, clicking a button in the studio throws an error by trying to instantiate a new popover.

Should we remove this error by allowing a studio button to take over the `popoverManager` if the existing one has no curtain behind it.

I presume visual improvements are more on the back burner; an ideal solution may be implementing a visual difference between popovers with a curtain and those without.

**Comment by jespertheend** [comment]
This is being tracked at #262 :)
