### ISSUE TITLE
Browsers lacking required API support don't throw notification

### ISSUE THREAD

**Issue by maxmmyron** [rendajs/Renda#516]
It seems like a few primary features in the studio are unsupported by some browsers: 
- `window.showDirectoryPicker()`: unsupported on Firefox, Webkit, mobile (in general)
- `WebGPU`: unsupported by default in most browsers right now
  - _usually supported w/ enabled flag_; could be possible to query browser version if all other guards check out and direct user to enable WebGPU flag.
- IDBFactory `databases()`: unsupported by Firefox

I'm a Firefox regular, so it wasn't immediately clear that my browser didn't support some features when the studio was unresponsive.

**Comment by jespertheend** [comment]
I initially figured it would take a while before I would have a MVP ready, at least as long if not longer for webgpu to become stable. But now that it's getting close this should probably be added yeah. Would be nice for older browsers as well regardless of whether WebGPU is supported everywhere or not.

**Comment by jespertheend** [comment]
In the case of `showDirectoryPicker` I think it's best to make the button greyed out. And then add a tooltip saying "Your browser does not support reading and writing to directories on disk."

`databases()` can just use a try catch I think? But there will probably be some issues with this approach.

WebGPU I'm not sure, the plan was to add WebGL fallback support but this takes a lot of time, and I'm not sure what will happen sooner, a WebGL implementation or WebGPU being supported universally.
