### ISSUE TITLE
ContextMenu submenus are toggled through parent MenuItem hover

### ISSUE THREAD

**Issue by maxmmyron** [rendajs/Renda#539]
Closely related to #531; ideal fix should address that & this.

Moving the mouse off of a MenuItem with an active submenu will not remove that submenu:

https://user-images.githubusercontent.com/41480159/231719766-e65ae0d6-374e-4b53-83b1-d00e3c1f5bdb.mp4

Seems like an active submenu will only be removed from the DOM through one of the two actions:
1. toggling another submenu on the same "menu level" as the submenu's parent (e.g. hovering over the "workspaces" menuItem with active "add tab" submenu)
2. clicking a MenuItem (noted in #531)

Ideally, a submenu should be created on parent MenuItem `mouseenter`, and removed on `mouseexit`. 

Alternatively, the entire menu structure could be present in the DOM upon creating root ContextMenu, and submenus would just be present through a CSS rule like `.menu-item:has(.submenu):hover > .submenu` (this may provide some nice hierarchy as well, instead of submenu being presented within the DOM as their own popover).

**Comment by maxmmyron** [comment]
Would it be possible to implement some level of delay between a `mouseexit`-type event and the popover disappearing? Such an action seems to be the default in most context menu interactions I've seen (i.e. Windows)

**Comment by jespertheend** [comment]
To be honest I kind of like it this way. But if enough users are annoyed by it then a cooldown could be added.
